### PR TITLE
Fix clippy lints and update dependencies

### PR DESCRIPTION
**Pull request by barafael**
Hi :)
first of all, thanks for making this great lib.
I noticed there were some outdated deps and clippy warnings. I did the chore of updating the deps and fixing the lints. Hope you like :) let me know what you think!

### CODE REVIEW

**Review by aatxe — APPROVED** [review]
Looks good to me!

**Comment by barafael** [comment]
Not sure if there is something I can do here to make CI pass?

**Comment by aatxe** [comment]
No, I believe it's because of Travis ending all the free open source support and I have been too busy to migrate things. I'll run all the tests manually.

**Comment by aatxe** [comment]
Ok, everything passed.

**Pull request merged**
